class lumify(
  $web_server_host= $lumify::params::web_server_host,
  $lumify_war_file= $lumify::params::lumify_war_file,
  $target_war_location=$lumify::params::target_war_location,
  $lumify_dir=$lumify::params::lumify_dir,
  $lumify_config_dir=$lumify::params::lumify_config_dir,
  $lumify_config_src_dir=$lumify::params::lumify_config_src_dir,
  $lumify_log_dir=$lumify::params::lumify_log_dir,
  $securegraph_user=$lumify::params::securegraph_user,
  $securegraph_password=$lumify::params::securegraph_password,
  $accumulo_user=$lumify::params::accumulo_user,
  $accumulo_password=$lumify::params::accumulo_password,
  $hadoop_namenode=$lumify::params::hadoop_namenode,
  $zookeeper_quorum=$lumify::params::zookeeper_quorum,
  $rabbitmq_nodes=$lumify::params::rabbitmq_nodes,
  $elastic_search_cluster_name=$lumify::params::elastic_search_cluster_name,
  $elastic_search_locations=$lumify::params::elastic_search_locations,
  $google_analytics_key=$lumify::params::google_analytics_key,
  $google_analytics_domain=$lumify::params::google_analytics_domain,
  $geocoder_bing_key=$lumify::params::geocoder_bing_key,
  $bing_clientId=$lumify::params::bing_clientId,
  $bing_secret=$lumify::params::bing_secret,
  $terms_of_use_title=$lumify::params::terms_of_use_title,
  $terms_of_use_html=$lumify::params::terms_of_use_html,
  $oauth_twitter_key=$lumify::params::oauth_twitter_key,
  $oauth_twitter_secret=$lumify::params::oauth_twitter_secret,
  $oauth_google_key=$lumify::params::oauth_google_key,
  $oauth_google_secret=$lumify::params::oauth_google_secret,
  $lumify_target_lib_dir=$lumify::params::lumify_target_lib_dir,
  $lumify_deployed_libs=$lumify::params::lumify_deployed_libs,
  $lumify_xml_file=$lumify::params::lumify_xml_file,
  $target_lumify_context=$lumify::params::target_lumify_context,
  $target_jar_location= $lumify::params::target_jar_location,
  $lumify_gpw_jars= $lumify::params::lumify_gpw_jars,
  $target_yarn_jar_location=$lumify::params::target_yarn_jar_location,
  $lumify_yarn_jars=$lumify::params::lumify_yarn_jars,
  $target_tools_jar_location=$lumify::params::target_tools_jar_location,
  $lumify_tools_jars=$lumify::params::lumify_tools_jars,
  $lumify_hdfs_gpw_directory=$lumify::params::lumify_hdfs_gpw_directory,
  $lumify_ontologies_dir=$lumify::params::lumify_ontologies_dir,
  $target_ontologies_dir=$lumify::params::target_ontologies_dir,

  $forgot_pass_server_hostname=$lumify::params::server_hostname,
  $forgot_pass_server_port=$lumify::params::server_port,
  $forgot_pass_server_username=$lumify::params::server_username,
  $forgot_pass_server_password=$lumify::params::server_password,
  $forgot_pass_from_email=$lumify::params::from_email,
  $forgot_pass_admin_email=$lumify::params::admin_email,

  $ldap_primary_server=$lumify::params::ldap_primary_server,
  $ldap_primary_port=$lumify::params::ldap_primary_port,
  $ldap_failover_server=$lumify::params::ldap_failover_server,
  $ldap_failover_port=$lumify::params::ldap_failover_port,
  $ldap_max_connections=$lumify::params::ldap_max_connections,
  $ldap_bind_password=$lumify::params::ldap_bind_password,
  $ldap_truststore=$lumify::params::ldap_truststore,
  $ldap_truststore_password=$lumify::params::ldap_truststore_password,
  $ldap_truststore_type=$lumify::params::ldap_truststore_type,
  $ldap_user_search_scope=$lumify::params::ldap_user_search_scope,
  $ldap_group_search_scope=$lumify::params::ldap_group_search_scope,
  $ldap_auth_clientdn_header=$lumify::params::ldap_auth_clientdn_header,
  $ldap_auth_clientcert_header=$lumify::params::ldap_auth_clientcert_header,
  $ldap_auth_required_attr=$lumify::params::ldap_auth_required_attr,
  $ldap_auth_required_attr_vals=$lumify::params::ldap_auth_required_attr_vals,
  $ldap_auth_required_groups=$lumify::params::ldap_auth_required_groups,
  $ldap_auth_username_attr=$lumify::params::ldap_auth_username_attr,
  $ldap_auth_displayname_attr=$lumify::params::ldap_auth_displayname_attr,

  $analysts_menuopt1_label=$lumify::params::analysts_menuopt1_label,
  $analysts_menuopt1_value=$lumify::params::analysts_menuopt1_value,
  $analysts_menuopt2_label=$lumify::params::analysts_menuopt2_label,
  $analysts_menuopt2_value=$lumify::params::analysts_menuopt2_value,
  $analysts_menuopt3_label=$lumify::params::analysts_menuopt3_label,
  $analysts_menuopt3_value=$lumify::params::analysts_menuopt3_value,
  $analysts_menuopt4_label=$lumify::params::analysts_menuopt4_label,
  $analysts_menuopt4_value=$lumify::params::analysts_menuopt4_value,
  $analysts_enable_custom_img_collect=$lumify::params::analysts_enable_custom_img_collect,
  $analysts_enable_icon_pic=$lumify::params::analysts_enable_icon_pic,
  $analysts_thmbnail_width=$lumify::params::analysts_thmbnail_width,
  $analysts_thmbnail_height=$lumify::params::analysts_thmbnail_height,
  $analysts_include_props=$lumify::params::analysts_include_props,
  $analysts_include_subtitle=$lumify::params::analysts_include_subtitle,
  $analysts_include_time=$lumify::params::analysts_include_time,
  $analysts_include_img_url=$lumify::params::analysts_include_img_url,
  $analysts_include_visib=$lumify::params::analysts_include_visib,
  $analysts_include_visib_label=$lumify::params::analysts_include_visib_label,
  $analysts_acc_service_url=$lumify::params::analysts_acc_service_url,
  $analysts_acc_param_name=$lumify::params::analysts_acc_param_name,
  $analysts_acc_truststore_path=$lumify::params::analysts_acc_truststore_path,
  $analysts_acc_truststore_password=$lumify::params::analysts_acc_truststore_password,
  $analysts_acc_disable_hostname_verif=$lumify::params::analysts_acc_disable_hostname_verif,

  $lumify_logs_dir=$lumify::params::lumify_logs_dir,

  $lumify_version=$lumify::params::lumify_version

)
inherits lumify::params
{
}
